- name: "t: feature"
  color: "1B9AAA"
  description: "New functionality or enhancement"
- name: "t: bug"
  color: "E63946"
  description: "Defect or regression"
- name: "t: refactor"
  color: "F4A261"
  description: "Refactoring or restructuring"
- name: "t: discussion"
  color: "118AB2"
  description: "Architecture or product discussion"
- name: "t: chore"
  color: "6C757D"
  description: "Maintenance or cleanup"
- name: "t: docs"
  color: "4EA8DE"
  description: "Documentation changes"
- name: "s: desktop"
  color: "3A86FF"
  description: "Desktop app"
- name: "s: cli"
  color: "FFBE0B"
  description: "CLI app"
- name: "s: server"
  color: "2A9D8F"
  description: "Server backend"
- name: "s: core"
  color: "8D99AE"
  description: "Core shared logic"
- name: "s: db"
  color: "7F5539"
  description: "Database"
- name: "s: keystore"
  color: "4D908E"
  description: "Keystore and secrets"
- name: "s: ci"
  color: "457B9D"
  description: "CI or automation"
- name: "s: repo"
  color: "ADB5BD"
  description: "Repository meta changes"
