name: Chore / tech debt
description: Maintenance, refactors, or cleanup
title: "[chore] "
labels: ["type/chore"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - desktop
        - cli
        - server
        - core
        - db
        - keystore
        - ci
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What should be improved or cleaned up?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Use checkboxes (- [ ]) where possible.
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Notes / links
    validations:
      required: false
