import { computed, isRef } from "vue";

type AppBindingsOptions = {
  core: Record<string, unknown>;
  computedState: Record<string, unknown>;
  statusBanners: Record<string, unknown>;
  selectionState: Record<string, unknown>;
  storageState: Record<string, unknown>;
  vaultState: Record<string, unknown>;
  foldersState: Record<string, unknown>;
  createState: Record<string, unknown>;
  detailState: Record<string, unknown>;
  layoutState: Record<string, unknown>;
  itemActions: Record<string, unknown>;
  storageActions: Record<string, unknown>;
  settingsActions: Record<string, unknown>;
  authFlow: Record<string, unknown>;
  personalUnlock: Record<string, unknown>;
  paletteState: Record<string, unknown>;
  sessionState: Record<string, unknown>;
  toastState: Record<string, unknown>;
  confirmState: Record<string, unknown>;
  misc: Record<string, unknown>;
};

export function useAppBindings(options: AppBindingsOptions) {
  const {
    core,
    computedState,
    statusBanners,
    selectionState,
    storageState,
    vaultState,
    foldersState,
    createState,
    detailState,
    layoutState,
    itemActions,
    storageActions,
    settingsActions,
    authFlow,
    personalUnlock,
    paletteState,
    sessionState,
    toastState,
    confirmState,
    misc,
  } = options;
  const shellBindings = {
    uiSettings: core.uiSettings,
    storageDropdownOpen: storageActions.storageDropdownOpen,
    storages: storageState.storages,
    remoteStorages: storageState.remoteStorages,
    localStorageRef: storageState.localStorage ?? storageState.localStorageRef,
    showLocalSection: storageState.showLocalSection,
    hasLocalVaults: storageState.hasLocalVaults,
    selectedStorageId: selectionState.selectedStorageId,
    currentStorage: selectionState.currentStorage,
    getSyncStatus: storageState.getSyncStatus,
    storageSyncErrors: storageState.storageSyncErrors,
    toggleStorageDropdown: storageActions.toggleStorageDropdown,
    closeStorageDropdown: storageActions.closeStorageDropdown,
    openAddStorageWizard: storageActions.openAddStorageWizard,
    openStorageSettings: storageActions.openStorageSettings,
    openCreateLocalVault: storageActions.openCreateLocalVault,
    switchStorage: storageActions.switchStorage,
    vaultDropdownOpen: storageActions.vaultDropdownOpen,
    vaults: vaultState.vaults,
    listLoading: core.listLoading,
    personalVaults: vaultState.personalVaults,
    sharedVaults: vaultState.sharedVaults,
    selectedVaultId: selectionState.selectedVaultId,
    toggleVaultDropdown: storageActions.toggleVaultDropdown,
    closeVaultDropdown: storageActions.closeVaultDropdown,
    switchVault: storageActions.switchVault,
    openCreateVault: storageActions.openCreateVault,
    categories: selectionState.categories,
    categoryCounts: selectionState.categoryCounts,
    selectedCategory: selectionState.selectedCategory,
    selectCategory: selectionState.selectCategory,
    folderTree: foldersState.folderTree,
    expandedFolders: foldersState.expandedFolders,
    selectedFolder: foldersState.selectedFolder,
    itemsWithoutFolder: foldersState.itemsWithoutFolder,
    toggleFolder: foldersState.toggleFolder,
    openFolderMenu: foldersState.openFolderMenu,
    selectFolderFilter: foldersState.selectFolderFilter,
    listPanel: layoutState.listPanel,
    filteredItems: selectionState.filteredItems,
    totalListHeight: layoutState.totalListHeight,
    listOffset: layoutState.listOffset,
    visibleItems: layoutState.visibleItems,
    selectedItemId: selectionState.selectedItemId,
    vaultContextLabel: selectionState.vaultContextLabel,
    isSharedVault: selectionState.isSharedVault,
    onListScroll: layoutState.onListScroll,
    selectItemById: selectionState.selectItemById,
    openCreateModal: createState.openCreateModal,
    emptyTrash: itemActions.emptyTrash,
    showOfflineBanner: statusBanners.showOfflineBanner,
    showSessionExpiredBanner: statusBanners.showSessionExpiredBanner,
    showPersonalLockedBanner: statusBanners.showPersonalLockedBanner,
    showSyncErrorBanner: statusBanners.showSyncErrorBanner,
    syncErrorMessage: statusBanners.syncErrorMessage,
    pendingChangesCount: statusBanners.pendingChangesCount,
    handleBannerSignIn: authFlow.handleBannerSignIn,
    openPersonalUnlock: personalUnlock.openPersonalUnlock,
    handleResetPersonal: personalUnlock.handleResetPersonal,
    runRemoteSync: core.runRemoteSync ?? storageState.runRemoteSync,
    lastSyncTime: core.lastSyncTime,
    openSettings: core.openSettings,
    listWidth: layoutState.listWidth,
    isResizingDetails: layoutState.isResizingDetails,
    startResizeDetails: layoutState.startResizeDetails,
    createModalOpen: createState.createModalOpen,
    createMode: createState.createMode,
    createItemVaultId: createState.createItemVaultId,
    createItemType: createState.createItemType,
    createItemTitle: createState.createItemTitle,
    createItemFolder: createState.createItemFolder,
    kvFilter: createState.kvFilter,
    advancedOpen: createState.advancedOpen,
    createVaultName: createState.createVaultName,
    createVaultKind: createState.createVaultKind,
    createVaultCachePolicy: createState.createVaultCachePolicy,
    createVaultDefault: createState.createVaultDefault,
    showFolderSuggestions: foldersState.showFolderSuggestions,
    flatFolderPaths: foldersState.flatFolderPaths,
    createItemFields: createState.createItemFields,
    filteredKvFields: createState.filteredKvFields,
    mainFields: createState.mainFields,
    advancedFields: createState.advancedFields,
    customFields: createState.customFields,
    typeOptions: createState.typeOptions,
    typeGroups: createState.typeGroups,
    createVaultError: createState.createVaultError,
    createItemError: createState.createItemError,
    createItemErrorKey: createState.createItemErrorKey,
    createItemBusy: createState.createItemBusy,
    createItemValid: createState.createItemValid,
    createVaultBusy: createState.createVaultBusy,
    createVaultValid: createState.createVaultValid,
    createEditingItemId: createState.createEditingItemId,
    revealedFields: detailState.revealedFields,
    altRevealAll: misc.altRevealAll,
    t: core.t,
    getFieldLabel: createState.getFieldLabel,
    addCustomField: createState.addCustomField,
    removeField: createState.removeField,
    buildPayload: createState.buildPayload,
    applyPayload: createState.applyPayload,
    submitCreate: createState.submitCreate,
    detailsPanel: layoutState.detailsPanel,
    query: selectionState.query,
    detailLoading: detailState.detailLoading,
    itemDetailError: core.itemDetailError,
    selectedItem: detailState.selectedItem,
    detailSections: detailState.detailSections,
    historyEntries: detailState.historyEntries,
    historyLoading: detailState.historyLoading,
    historyError: detailState.historyError,
    selectedItemConflict: computedState.selectedItemConflict,
    isRevealed: detailState.isRevealed,
    toggleReveal: detailState.toggleReveal,
    copyField: itemActions.copyField,
    copyEnv: itemActions.copyEnv,
    copyJson: itemActions.copyJson,
    copyRaw: itemActions.copyRaw,
    copyHistoryPassword: itemActions.copyHistoryPassword,
    restoreHistoryVersion: itemActions.restoreHistoryVersion,
    fetchHistoryPayload: detailState.fetchHistoryPayload,
    openExternal: core.openExternal,
    openEditItem: () => {
      const payloadOverride =
        isRef(detailState.timeTravelDraftPayload) && detailState.timeTravelHasDraft?.value
          ? detailState.timeTravelDraftPayload.value
          : null;
      createState.openEditItem(payloadOverride ?? undefined);
    },
    deleteItem: itemActions.deleteItem,
    selectedItemDeleted: computedState.selectedItemDeleted,
    restoreItem: itemActions.restoreItem,
    purgeItem: itemActions.purgeItem,
    selectedVaultName: selectionState.selectedVaultName,
    resolveConflict: misc.resolveConflict,
    timeTravelActive: detailState.timeTravelActive,
    timeTravelIndex: detailState.timeTravelIndex,
    timeTravelPayload: detailState.timeTravelPayload,
    timeTravelBasePayload: detailState.timeTravelBasePayload,
    timeTravelLoading: detailState.timeTravelLoading,
    timeTravelError: detailState.timeTravelError,
    timeTravelHasDraft: detailState.timeTravelHasDraft,
    applyTimeTravelField: detailState.applyTimeTravelField,
    openTimeTravel: detailState.openTimeTravel,
    closeTimeTravel: detailState.closeTimeTravel,
    setTimeTravelIndex: detailState.setTimeTravelIndex,
  };

  const modalBindings = {
    fatalError: core.fatalError,
    t: core.t,
    runBootstrap: core.runBootstrap,
    appStatus: core.appStatus,
    showSetupModal: computedState.showSetupModal,
    setupStep: authFlow.setupStep,
    setupFlow: authFlow.setupFlow,
    setupPassword: authFlow.setupPassword,
    setupConfirm: authFlow.setupConfirm,
    setupPasswordMode: authFlow.setupPasswordMode,
    connectServerUrl: authFlow.connectServerUrl,
    setupError: authFlow.setupError,
    setupBusy: authFlow.setupBusy,
    connectVerification: authFlow.connectVerification,
    connectStatus: authFlow.connectStatus,
    connectError: authFlow.connectError,
    connectOldFp: authFlow.connectOldFp,
    connectNewFp: authFlow.connectNewFp,
    connectBusy: authFlow.connectBusy,
    connectLoginId: authFlow.connectLoginId,
    logoUrl: core.logoUrl,
    normalizeServerUrl: authFlow.normalizeServerUrl,
    startLocalSetup: authFlow.startLocalSetup,
    startConnect: authFlow.startConnect,
    backToWelcome: authFlow.backToWelcome,
    createMasterPassword: authFlow.createMasterPassword,
    showAuthMethodSelection: authFlow.showAuthMethodSelection,
    trustFingerprint: authFlow.trustFingerprint,
    openExternal: core.openExternal,
    copyToClipboard: core.copyToClipboard,
    showUnlock: computedState.showUnlock,
    password: core.password,
    unlockBusy: sessionState.unlockBusy,
    settings: core.settings,
    keystoreStatus: core.keystoreStatus,
    autoUnlockError: core.autoUnlockError,
    error: core.error,
    identityAlertOpen: core.identityAlertOpen,
    identityAlertTitle: core.identityAlertTitle,
    identityAlertMessage: core.identityAlertMessage,
    doUnlock: core.doUnlock,
    unlockWithBiometrics: sessionState.unlockWithBiometrics,
    personalUnlockOpen: personalUnlock.personalUnlockOpen,
    personalUnlockPassword: personalUnlock.personalUnlockPassword,
    personalUnlockBusy: personalUnlock.personalUnlockBusy,
    personalUnlockError: personalUnlock.personalUnlockError,
    unlockPersonalVaults: personalUnlock.unlockPersonalVaults,
    paletteOpen: paletteState.paletteOpen,
    paletteQuery: paletteState.paletteQuery,
    paletteIndex: paletteState.paletteIndex,
    paletteItems: paletteState.paletteItems,
    settingsOpen: core.settingsOpen,
    settingsInitialTab: core.settingsInitialTab,
    rememberEnabled: computedState.rememberEnabled,
    locale: core.locale,
    updateSettings: settingsActions.updateSettings,
    testBiometrics: settingsActions.testBiometrics,
    rebindBiometrics: settingsActions.rebindBiometrics,
    showLocalSection: storageState.showLocalSection,
    hasLocalVaults: storageState.hasLocalVaults,
    getStorageInfo: storageState.getStorageInfo,
    handleSignOut: storageActions.handleSignOut,
    handleSignIn: storageActions.handleSignIn,
    handleRemoveServer: storageActions.handleRemoveServer,
    handleClearData: storageActions.handleClearData,
    handleFactoryReset: storageActions.handleFactoryReset,
    handleStorageReveal: storageActions.handleStorageReveal,
    openAddStorageWizard: storageActions.openAddStorageWizard,
    openCreateLocalVault: storageActions.openCreateLocalVault,
    handleSyncNow: storageActions.handleSyncNow,
    handleResetSyncCursor: storageActions.handleResetSyncCursor,
    storages: storageState.storages,
    toast: toastState.toast,
    toastActionLabel: toastState.toastActionLabel,
    toastAction: toastState.toastAction,
    createMode: createState.createMode,
    createModalOpen: createState.createModalOpen,
    createItemVaultId: createState.createItemVaultId,
    createItemType: createState.createItemType,
    createItemTitle: createState.createItemTitle,
    createItemFolder: createState.createItemFolder,
    kvFilter: createState.kvFilter,
    advancedOpen: createState.advancedOpen,
    createVaultName: createState.createVaultName,
    createVaultKind: createState.createVaultKind,
    createVaultCachePolicy: createState.createVaultCachePolicy,
    createVaultDefault: createState.createVaultDefault,
    showFolderSuggestions: foldersState.showFolderSuggestions,
    vaults: vaultState.vaults,
    flatFolderPaths: foldersState.flatFolderPaths,
    createItemFields: createState.createItemFields,
    filteredKvFields: createState.filteredKvFields,
    mainFields: createState.mainFields,
    advancedFields: createState.advancedFields,
    customFields: createState.customFields,
    typeOptions: createState.typeOptions,
    typeGroups: createState.typeGroups,
    createVaultError: createState.createVaultError,
    createItemError: createState.createItemError,
    createItemErrorKey: createState.createItemErrorKey,
    createItemBusy: createState.createItemBusy,
    createItemValid: createState.createItemValid,
    createVaultBusy: createState.createVaultBusy,
    createVaultValid: createState.createVaultValid,
    createEditingItemId: createState.createEditingItemId,
    revealedFields: detailState.revealedFields,
    altRevealAll: misc.altRevealAll,
    getFieldLabel: createState.getFieldLabel,
    addCustomField: createState.addCustomField,
    removeField: createState.removeField,
    buildPayload: createState.buildPayload,
    applyPayload: createState.applyPayload,
    submitCreate: createState.submitCreate,
    syncBusy: storageState.syncBusy,
    syncError: storageState.syncError,
    folderMenuOpen: foldersState.folderMenuOpen,
    folderMenuPosition: foldersState.folderMenuPosition,
    closeFolderMenu: foldersState.closeFolderMenu,
    openRenameFolderModal: foldersState.openRenameFolderModal,
    copyFolderPath: foldersState.copyFolderPath,
    renameFolderModalOpen: foldersState.renameFolderModalOpen,
    renameFolderNewName: foldersState.renameFolderNewName,
    renameFolderOldPath: foldersState.renameFolderOldPath,
    renameFolderNewPath: foldersState.renameFolderNewPath,
    affectedItemsCount: foldersState.affectedItemsCount,
    renameFolderBusy: foldersState.renameFolderBusy,
    renameFolderError: foldersState.renameFolderError,
    submitRenameFolder: foldersState.submitRenameFolder,
    deleteStorageOpen: storageActions.deleteStorageOpen,
    deleteStorageInfo: storageActions.deleteStorageInfo,
    deleteStorageBusy: storageActions.deleteStorageBusy,
    confirmDeleteStorage: storageActions.confirmDeleteStorage,
    confirmDisconnectStorage: storageActions.confirmDisconnectStorage,
    confirmOpen: confirmState.confirmOpen,
    confirmTitle: confirmState.confirmTitle,
    confirmMessage: confirmState.confirmMessage,
    confirmConfirmLabel: confirmState.confirmConfirmLabel,
    confirmCancelLabel: confirmState.confirmCancelLabel,
    confirmBusy: confirmState.confirmBusy,
    confirmInputExpected: confirmState.confirmInputExpected,
    confirmInputLabel: confirmState.confirmInputLabel,
    confirmInputPlaceholder: confirmState.confirmInputPlaceholder,
    handleConfirm: confirmState.handleConfirm,
    authMethodOpen: authFlow.authMethodOpen,
    availableMethods: authFlow.availableMethods,
    handleSelectPassword: authFlow.handleSelectPassword,
    handleSelectOidc: authFlow.handleSelectOidc,
    passwordLoginOpen: authFlow.passwordLoginOpen,
    passwordLoginBusy: authFlow.passwordLoginBusy,
    passwordLoginError: authFlow.passwordLoginError,
    handlePasswordAuth: authFlow.handlePasswordAuth,
  };

  const unwrapValue = (value: unknown) => (isRef(value) ? value.value : value);
  const unwrapBindings = (
    bindings: Record<string, unknown>,
    modelKeys: Set<string>,
  ) =>
    computed(() =>
      Object.fromEntries(
        Object.entries(bindings).map(([key, value]) => [
          key,
          modelKeys.has(key) ? value : unwrapValue(value),
        ]),
      ),
    );

  const shellModelKeys = new Set([
    "uiSettings",
    "createModalOpen",
    "createItemVaultId",
    "createItemType",
    "createItemTitle",
    "createItemFolder",
    "kvFilter",
    "advancedOpen",
    "createVaultName",
    "createVaultKind",
    "createVaultCachePolicy",
    "createVaultDefault",
    "showFolderSuggestions",
    "query",
  ]);

  const modalModelKeys = new Set([
    "setupStep",
    "setupFlow",
    "setupPassword",
    "setupConfirm",
    "connectServerUrl",
    "password",
    "personalUnlockPassword",
    "paletteOpen",
    "paletteQuery",
    "paletteIndex",
    "settingsOpen",
    "createModalOpen",
    "createItemVaultId",
    "createItemType",
    "createItemTitle",
    "createItemFolder",
    "kvFilter",
    "advancedOpen",
    "createVaultName",
    "createVaultKind",
    "createVaultCachePolicy",
    "createVaultDefault",
    "showFolderSuggestions",
    "renameFolderModalOpen",
    "renameFolderNewName",
    "deleteStorageOpen",
    "confirmOpen",
    "identityAlertOpen",
    "authMethodOpen",
    "passwordLoginOpen",
  ]);

  const shellBindingsResolved = unwrapBindings(shellBindings, shellModelKeys);
  const modalBindingsResolved = unwrapBindings(modalBindings, modalModelKeys);

  return { shellBindings: shellBindingsResolved, modalBindings: modalBindingsResolved };
}
