[package]
name = "zann-client"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[dependencies]
base64 = { version = "0.22", optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
data-encoding = { version = "2", optional = true }
ed25519-dalek = { version = "2", optional = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots"], optional = true }
rand = { version = "0.8", optional = true }
same-file = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
serde_yaml = { version = "0.9", optional = true }
sha2 = { version = "0.10", optional = true }
tempfile = { version = "3", optional = true }
thiserror = { version = "1", optional = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"], optional = true }
url = { version = "2", optional = true }
uuid = { version = "1", features = ["v7", "serde"], optional = true }
zeroize = { version = "1", optional = true }

zann-core = { path = "../zann-core", optional = true }
zann-crypto = { path = "../zann-crypto", optional = true }
zann-keystore = { path = "../zann-keystore", default-features = false, features = ["secret-store"], optional = true }

[features]
default = ["remote"]
app = ["sync", "delivery"]
delivery = [
  "dep:serde",
  "dep:serde_yaml",
]
auth-lock = ["config"]
session = [
  "auth-lock",
  "remote",
  "dep:tokio",
  "dep:uuid",
]
sync = [
  "session",
  "dep:zann-crypto",
]
remote = [
  "dep:base64",
  "dep:chrono",
  "dep:data-encoding",
  "dep:ed25519-dalek",
  "dep:reqwest",
  "dep:rand",
  "dep:serde",
  "dep:serde_json",
  "dep:sha2",
  "dep:zeroize",
  "dep:uuid",
  "dep:zann-core",
]
config = [
  "dep:chrono",
  "dep:data-encoding",
  "dep:same-file",
  "dep:serde",
  "dep:serde_json",
  "dep:sha2",
  "dep:tempfile",
  "dep:thiserror",
  "dep:url",
  "dep:uuid",
  "dep:zeroize",
  "dep:zann-core",
]
os-credentials = [
  "config",
  "dep:zann-keystore",
]

[dev-dependencies]
mockito = "1.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
